### ISSUE TITLE
Compiled binaries?

### ISSUE THREAD

**Issue by polarbub** [mailmindlin/winACD#1]
Is there a pre compiled exe / how do I compile myself?

**Comment by crackajack77** [comment]
Yes please compile binaries! Need help for my trusty ACD30" on Windows 10.

**Comment by polarbub** [comment]
If you go to the [source forge page](https://sourceforge.net/projects/winacd/) you can get an MSI in a zip. It might work as this is just source

**Comment by mailmindlin** [comment]
The source forge page is probably a better source than this one, as I was convinced I built it right on my machine.

**Comment by polarbub** [comment]
@mailmindlin is this just a mirror of the sourceforge SVN?

**Comment by polarbub** [comment]
Nope, I'll try and get this to build on my own.

**Comment by sambacore** [comment]
@polarbub Did you ever get this built?

**Comment by polarbub** [comment]
I never did manage to get it compiled. In the end I wound up just using [Brightness Controller](https://www.holstschumacher.dk/p/brightness-controller.html) which allows me to set the brightness of my ACD, but it doesn't do any of the fancy power button stuff. The latest beta version works on Windows 10.
